### ISSUE TITLE
Does not generate 4 tones

### ISSUE THREAD

**Issue by junglerhino37** [berteh/musescore-chordsToNotes#7]
I am running MuseScore 2.0.3 on Windows 7.
(Edit: Solved below, sort of)

![2017-02-11 18_47_50-musescore 2_ chords-to-notes_generator_simple-test](https://cloud.githubusercontent.com/assets/24379204/22858705/ab2a1c5a-f08a-11e6-8180-2cc23dbd5e6a.png)

**Comment by junglerhino37** [comment]
I decided to follow instructions and transpose up and back down. I had to reset the map key because F2 is volume on windows. Here is the result. 
![2017-02-11 18_58_20-musescore 2_ chords-to-notes_generator_simple-test](https://cloud.githubusercontent.com/assets/24379204/22858767/29394eda-f08c-11e6-81ad-923a871ad8bb.png)

**Comment by junglerhino37** [comment]
On the other hand, this does not fix every chord. When I applied the process to the chord_chart.mscz file in the test folder, here was the result:
![2017-02-11 19_00_11-musescore 2_ chord_chart](https://cloud.githubusercontent.com/assets/24379204/22858776/717352cc-f08c-11e6-8af9-ca8b527f842b.png)

**Comment by berteh** [comment]
Thanks for the report and tests. I had similar results on the same chord chart (see https://github.com/berteh/musescore-chordsToNotes/blob/master/test/Chord_Chart_afterGeneration.mscz).

Since the internal mechanism to parse chords notation was being updated into musescore when I wrote this plugin I didn't improve much on this, as the new parsing mechanism would allow to handle virtually any notation.

Unfortunately accessing this parsing mechanism from the script (i.e. in the QML) part of musescore is above my software development time (need to create the whole API in musescore), so I won't be doing it anytime soon. Contributions / Alternatives are welcome, and I'll gladly review / commit any push related request.

Berteh.

**Comment by junglerhino37** [comment]
Thanks for your work!

**Comment by berteh** [comment]
Thanks for your feedback.

As a similar feature is being integrated in the main release of MuseScore (finally, great!), I personnaly don't plan on supporting this script further. You are of course free to take over from me if you want to. Kindly let me know: https://github.com/musescore/MuseScore/pull/5129#issuecomment-601717806
